services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: fwm
      POSTGRES_USER: fwm
      POSTGRES_PASSWORD: change-me
      TZ: Australia/Melbourne
    env_file:
      - ../.env
    volumes:
      - ../pgdata:/var/lib/postgresql/data
    healthcheck:
      # $$ escapes so Compose doesn't expand at parse time
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  adminer:
    image: adminer
    depends_on:
      - db
    ports:
      - "8082:8080"
    restart: unless-stopped

  app:
    build:
      context: ..
      dockerfile: infra/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    environment:
      TZ: Australia/Melbourne   # keep only literals here
    volumes:
      - ../data:/app/data
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
